Get Data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
abstrak_df = pd.read_csv('/content/drive/MyDrive/prosaindata/uts/dataset-baru.csv')

In [4]:
df  = pd.DataFrame(abstrak_df[['Kategori','Abstrak']])

In [5]:
df.tail()

      Kategori                                            Abstrak
800  KOMPUTASI  Investasi saham selama ini memiliki resiko ker...
801  KOMPUTASI  Information Retrieval (IR) merupakan pengambil...
802  KOMPUTASI  Klasifikasi citra merupakan proses pengelompok...
803  KOMPUTASI  Identifikasi atribut pejalan kaki merupakan sa...
804  KOMPUTASI  Topik deteksi objek telah menarik perhatian ya...

Preprocessing Data

In [6]:
import nltk
import string
import re

In [7]:
def case_folding(abstrak):
    abstrak = abstrak.lower()
    return abstrak
df['abstrak_lower'] = df['Abstrak'].apply(lambda x: case_folding(x))

In [8]:
df.head()

,Kategori,Abstrak,abstrak_lower
0,RPL,Sistem informasi akademik (SIAKAD) merupaka...,sistem informasi akademik (siakad) merupaka...
1,RPL,Berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...
2,RPL,Web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...
3,KOMPUTASI,Penjadwalan kuliah di Perguruan Tinggi me...,penjadwalan kuliah di perguruan tinggi me...
4,RPL,Seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...

In [9]:
#import stopword
from nltk.corpus import stopwords 
nltk.download('stopwords')
stopwords_indonesia = stopwords.words('indonesian')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [10]:
#install and import pysastrawi
!pip install PySastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting PySastrawi
  Downloading PySastrawi-1.2.0-py2.py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.6/210.6 KB 7.2 MB/s eta 0:00:00
Installing collected packages: PySastrawi
Successfully installed PySastrawi-1.2.0

In [11]:
def cleaning(abstrak):
    symbols = ",!\"#$%&()*+-.…/:;<=>?@[\]^_`{|}~\n"
    abstrak = re.sub(r"\s—\s", "", abstrak)
    abstrak = re.sub(r"http\S+", "", abstrak)
    for i in symbols:
        abstrak = np.char.replace(abstrak, i, ' ')
    return abstrak
df['abstrak_clean'] = df['abstrak_lower'].apply(lambda x: cleaning(x))

In [12]:
df.head()

,Kategori,Abstrak,abstrak_lower,abstrak_clean
0,RPL,Sistem informasi akademik (SIAKAD) merupaka...,sistem informasi akademik (siakad) merupaka...,sistem informasi akademik siakad merupaka...
1,RPL,Berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...
2,RPL,Web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...
3,KOMPUTASI,Penjadwalan kuliah di Perguruan Tinggi me...,penjadwalan kuliah di perguruan tinggi me...,penjadwalan kuliah di perguruan tinggi me...
4,RPL,Seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...

In [13]:
def split(abstrak):
    return abstrak.split()
df['abstrak_split'] = df['abstrak_clean'].apply(lambda x: split(x))

In [14]:
df.head()

,Kategori,Abstrak,abstrak_lower,abstrak_clean,abstrak_split
0,RPL,Sistem informasi akademik (SIAKAD) merupaka...,sistem informasi akademik (siakad) merupaka...,sistem informasi akademik siakad merupaka...,"[sistem, informasi, akademik, siakad, merupaka..."
1,RPL,Berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...,"[berjalannya, koneksi, jaringan, komputer, den..."
2,RPL,Web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...,"[web, server, adalah, sebuah, perangkat, lunak..."
3,KOMPUTASI,Penjadwalan kuliah di Perguruan Tinggi me...,penjadwalan kuliah di perguruan tinggi me...,penjadwalan kuliah di perguruan tinggi me...,"[penjadwalan, kuliah, di, perguruan, tinggi, m..."
4,RPL,Seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...,"[seiring, perkembangan, teknologi, yang, ada, ..."

In [15]:
def stemming(abstrak):
  abstraks_clean = []    
  for word in abstrak:
      word = stemmer.stem(word)
      abstraks_clean.append(word)
  return abstraks_clean
df['abstrak_stem'] = df['abstrak_split'].apply(lambda x: stemming(x))

In [16]:
df.head()

,Kategori,Abstrak,abstrak_lower,abstrak_clean,abstrak_split,abstrak_stem
0,RPL,Sistem informasi akademik (SIAKAD) merupaka...,sistem informasi akademik (siakad) merupaka...,sistem informasi akademik siakad merupaka...,"[sistem, informasi, akademik, siakad, merupaka...","[sistem, informasi, akademik, siakad, rupa, si..."
1,RPL,Berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...,berjalannya koneksi jaringan komputer dengan l...,"[berjalannya, koneksi, jaringan, komputer, den...","[jalan, koneksi, jaring, komputer, dengan, lan..."
2,RPL,Web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...,web server adalah sebuah perangkat lunak serve...,"[web, server, adalah, sebuah, perangkat, lunak...","[web, server, adalah, buah, perangkat, lunak, ..."
3,KOMPUTASI,Penjadwalan kuliah di Perguruan Tinggi me...,penjadwalan kuliah di perguruan tinggi me...,penjadwalan kuliah di perguruan tinggi me...,"[penjadwalan, kuliah, di, perguruan, tinggi, m...","[jadwal, kuliah, di, guru, tinggi, rupa, masal..."
4,RPL,Seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...,seiring perkembangan teknologi yang ada diduni...,"[seiring, perkembangan, teknologi, yang, ada, ...","[iring, kembang, teknologi, yang, ada, dunia, ..."

In [17]:
abstrak = df['Abstrak']
X = df['abstrak_stem']
Y = df['Kategori'].values

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [33]:
# Inisialisasi objek TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Terapkan TfidfVectorizer pada dokumen
tfidf_matrix = tfidf_vectorizer.fit_transform(abstrak)

# Ubah matriks TF-IDF menjadi dataframe Pandas
df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out()
)

X = df_tfidf.values
print(df_tfidf)

      00  000  00001  0001  000505341  000506436  000792353  00086  00089  \
0    0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
1    0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
2    0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
3    0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
4    0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
..   ...  ...    ...   ...        ...        ...        ...    ...    ...
800  0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
801  0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
802  0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
803  0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0
804  0.0  0.0    0.0   0.0        0.0        0.0        0.0    0.0    0.0

     001  ...   zf  zona  zone  zoning  zoom  zucara  zungu   zâ   âµ   â¼
0    0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
1    0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
2    0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
3    0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
4    0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
..   ...  ...  ...   ...   ...     ...   ...     ...    ...  ...  ...  ...
800  0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
801  0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
802  0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
803  0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0
804  0.0  ...  0.0   0.0   0.0     0.0   0.0     0.0    0.0  0.0  0.0  0.0

[805 rows x 9167 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.1, random_state = 100)

In [25]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [26]:
print (" Accuracy : ", accuracy_score(y_test,y_pred))

 Accuracy :  0.8148148148148148

In [27]:
pca = PCA(n_components =30)

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

pca.explained_variance_ratio_

array([0.01903064, 0.01382074, 0.01198357, 0.00966306, 0.00849257,
       0.00794841, 0.00726456, 0.00693901, 0.00654376, 0.00638002,
       0.00628846, 0.00607767, 0.00591448, 0.00569535, 0.00540844,
       0.00531605, 0.00511692, 0.00494922, 0.00485554, 0.00473616,
       0.00459958, 0.00446884, 0.00438927, 0.00436289, 0.00426971,
       0.00419769, 0.00408897, 0.00393184, 0.00389051, 0.00383568])

Training model sesudah PCA

In [28]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [29]:
print ("Accuracy : ", accuracy_score(y_test,y_pred))

Accuracy :  0.8765432098765432